//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class login
    {
        /// <summary>
        /// model for login table
        /// </summary>
        public int userid { get; set; }
        [DisplayName("username")]
       
        [Required(ErrorMessage ="This field is required")]//validation message
        public string username { get; set; }
        [DataType(DataType.Password)]//represents data with symbols
        [Required(ErrorMessage = "This field is required")]
        public string password { get; set; }
        [DisplayName("Confirm Password")]
        [DataType(DataType.Password)]//represents data with symbols
        [Compare("password")]
        public string confirmpassword { get; set; }

        public string loginerrormessage { get; set; }
    }
}
